language: c

os:
- linux
- osx

compiler:
- gcc
- clang

before_script:
- |
  if [ ${TRAVIS_OS_NAME} = "linux" ]; then 
    sudo apt-get install libblas-dev
    sudo apt-get install liblapack-dev
  fi

script:
- mkdir -p build
- cd build
- cmake .. || travis_terminate 1
- make || travis_terminate 1
- make install || travis_terminate 1
- make CTEST_OUTPUT_ON_FAILURE=1 test

install: true
